const capabilities=[
["01","Kejuruteraan Produk Digital","Aplikasi web, PWA dan produk SaaS yang dibina berasaskan aliran operasi sebenar."],
["02","Sistem Perniagaan","Sistem operasi, aliran pesanan, pengurusan vendor, alat dalaman dan automasi."],
["03","AI & Automasi","Aliran kerja berbantu AI dan sistem generatif digunakan apabila ia memberi nilai yang boleh diukur."],
["04","Integrasi & Infrastruktur","API, pembayaran, notifikasi, cloud, identiti dan integrasi pihak ketiga."]];
const initiatives=[
{name:"BORIGN",type:"Service Operating System",body:"Platform kitar hayat perkhidmatan daripada permintaan dan penemuan keupayaan hingga pelaksanaan, bukti, penyempurnaan dan kepercayaan.",url:"https://borign.com"},
{name:"EON",type:"Event Organizer Operating System",body:"Aliran kerja bersepadu untuk acara, vendor dan operasi penganjuran.",url:"https://eon-platform.kaerogroup.workers.dev"},
{name:"ORDRE",type:"Commerce Order Operating System",body:"Enjin pesanan offline-first untuk pelaksanaan pesanan merentas saluran jualan.",url:"https://ordre-pos.kaerogroup.workers.dev"},
{name:"ANGLR",type:"Ekosistem digital memancing",body:"Aliran kerja komuniti, bukti tangkapan dan penyertaan pertandingan memancing.",url:"https://anglr-platform.kaerogroup.workers.dev"}];
const evidence=[
["Pemilikan produk","Kami membina dan mengoperasikan produk sendiri supaya keputusan produk dan teknikal diuji terhadap keperluan operasi sebenar."],
["Penghantaran production","Platform terpilih dihantar melalui source control, build gate automatik dan deployment cloud yang boleh disemak."],
["Pemodelan operasi","Sistem bermula dengan aliran kerja, tanggungjawab, bukti dan keadaan proses — bukan himpunan skrin terpisah."],
["Pengurusan jangka panjang","Produk distruktur untuk iterasi, penyelenggaraan, integrasi dan penambahbaikan operasi berterusan."]];
const engagement=[
["Pembangunan Tersuai","Aplikasi dan sistem yang dibina khusus untuk organisasi atau masalah operasi tertentu."],
["Pelaksanaan Produk","Konfigurasi dan pelaksanaan produk UNIRAS atau keupayaan teknologi sedia guna."],
["Rakan Teknologi","Pembangunan berterusan, integrasi, pemodenan dan pengurusan teknikal jangka panjang."]];
export default function MalayHome(){return <main>
<header className="site-header shell"><a className="brand" href="#top"><span className="brand-mark">U</span><span>UNIRAS</span></a><nav><a href="#capabilities">Keupayaan</a><a href="#products">Produk</a><a href="#approach">Pendekatan</a><span className="language-switch"><a href="/">EN</a><span className="active">BM</span></span><a href="#contact" className="nav-cta">Mulakan projek</a></nav></header>
<section className="hero shell" id="top"><div className="hero-grid"><div><div className="eyebrow">UNIRAS SDN. BHD. · Malaysia</div><h1>Perisian yang dibina mengikut cara sebenar perniagaan beroperasi.</h1><p className="hero-copy">Kami mereka bentuk dan membina produk digital, aplikasi dan sistem operasi — daripada aliran kerja dan logik domain hingga antaramuka, integrasi dan deployment.</p><div className="hero-actions"><a className="button primary" href="#products">Lihat produk</a><a className="button secondary" href="#contact">Bincang sistem</a></div></div><aside className="hero-panel"><p className="panel-label">Keupayaan teras</p><div className="panel-row"><span>01</span><strong>Kejuruteraan Produk</strong></div><div className="panel-row"><span>02</span><strong>Sistem Perniagaan</strong></div><div className="panel-row"><span>03</span><strong>AI & Automasi</strong></div><div className="panel-row"><span>04</span><strong>Cloud & Integrasi</strong></div></aside></div><div className="hero-rule"/><div className="hero-meta"><span>Aliran kerja dahulu</span><span>Kejelasan operasi</span><span>Kejuruteraan berorientasikan production</span></div></section>
<section className="section intro"><div className="shell intro-grid"><div><div className="section-kicker">Syarikat</div><h2>Teknologi yang dibina berasaskan operasi.</h2></div><div className="intro-copy"><p>UNIRAS SDN. BHD. membina perisian berdasarkan operasi sebenar. Kami bermula dengan proses, tanggungjawab dan keputusan yang perlu disokong oleh sistem, kemudian membina produk digital di sekeliling model tersebut.</p><p>Kerja kami merangkumi produk teknologi milik sendiri dan pembangunan aplikasi tersuai untuk organisasi yang memerlukan aliran kerja lebih jelas dan sistem yang boleh berkembang.</p></div></div></section>
<section className="section shell" id="capabilities"><div className="section-kicker">Keupayaan</div><div className="section-heading"><h2>Daripada masalah operasi kepada sistem yang berfungsi.</h2><p>Keupayaan kami merangkumi kejuruteraan produk, sistem aliran kerja, operasi berbantu AI dan integrasi.</p></div><div className="capability-grid">{capabilities.map(([n,t,b])=><article className="capability" key={t}><span>{n}</span><h3>{t}</h3><p>{b}</p></article>)}</div></section>
<section className="section products-section" id="products"><div className="shell"><div className="section-kicker light">Produk & inisiatif teknologi</div><div className="section-heading light"><h2>Kami turut membina produk sendiri.</h2><p>Produk milik sendiri menunjukkan pendekatan kami terhadap pemodelan domain, aliran operasi dan kejuruteraan produk jangka panjang.</p></div><article className="featured-product"><div className="featured-product-top"><span className="status-pill active">Produk beroperasi</span><span className="product-index">01</span></div><div className="featured-product-grid"><div><h3>LOOKAL</h3><p className="product-type">Platform teknologi kreatif</p></div><div><p>Penghasilan kreatif berbantu AI secara berstruktur untuk komunikasi perniagaan dan aliran kerja kempen.</p><div className="product-proof"><span>Produk milik sendiri</span><span>Aliran kerja berbantu AI</span><span>Production</span></div><a className="product-cta" href="https://lookal.tech" target="_blank" rel="noreferrer">Buka LOOKAL ↗</a></div></div></article><div className="initiative-list">{initiatives.map((p,i)=><article className="initiative" key={p.name}><span className="product-index">0{i+2}</span><div><h3>{p.name}</h3><p className="product-type">{p.type}</p></div><p>{p.body}</p><div className="initiative-actions"><span className="status-pill">Dalam pembangunan</span><a className="product-cta compact" href={p.url} target="_blank" rel="noreferrer">Buka projek ↗</a></div></article>)}</div></div></section>
<section className="section shell evidence-section"><div className="section-kicker">Bukti penyampaian</div><div className="section-heading"><h2>Dibina untuk bergerak melepasi prototaip.</h2><p>Model penyampaian kami menghubungkan pemikiran produk dengan disiplin kejuruteraan, deployment production dan pengurusan berterusan.</p></div><div className="evidence-grid">{evidence.map(([t,b],i)=><article key={t}><span>0{i+1}</span><h3>{t}</h3><p>{b}</p></article>)}</div></section>
<section className="section shell" id="approach"><div className="section-kicker">Cara kami membina</div><div className="section-heading"><h2>Kami tidak bermula dengan skrin.</h2><p>Reka bentuk antaramuka dibuat selepas kami memahami operasi yang perlu disokong oleh perisian.</p></div><div className="process">{["Operasi","Aliran Kerja","Model Domain","Sistem","Antaramuka"].map((x,i)=><div className="process-step" key={x}><span>0{i+1}</span><strong>{x}</strong></div>)}</div><div className="statement">Masalah sebenar <span>→</span> aliran kerja jelas <span>→</span> sistem boleh dipercayai <span>→</span> hasil yang boleh diukur.</div></section>
<section className="section trust-band"><div className="shell trust-grid"><div><span className="trust-number">01</span><strong>Static-first apabila sesuai</strong><p>Pengalaman awam yang pantas, tahan lasak dan mudah dioperasikan.</p></div><div><span className="trust-number">02</span><strong>Penghantaran cloud-native</strong><p>Deployment moden, API dan infrastruktur terurus dipilih mengikut keperluan sistem.</p></div><div><span className="trust-number">03</span><strong>Keselamatan sejak reka bentuk</strong><p>Identiti, kebenaran akses, audit dan sempadan data dipertimbangkan dari awal.</p></div></div></section>
<section className="section shell engagement"><div className="section-kicker">Cara bekerjasama</div><div className="section-heading"><h2>Tiga cara bekerjasama dengan UNIRAS.</h2><p>Pilih model yang sesuai dengan masalah operasi, kematangan produk dan struktur pemilikan.</p></div><div className="engagement-grid">{engagement.map(([t,b],i)=><div key={t}><span>0{i+1}</span><h3>{t}</h3><p>{b}</p></div>)}</div></section>
<section className="contact" id="contact"><div className="shell contact-inner"><div><div className="section-kicker light">Mulakan perbincangan</div><h2>Ada operasi yang sepatutnya boleh berfungsi dengan lebih baik?</h2><p>Ceritakan aliran kerja, masalah atau sistem yang anda mahu perbaiki. Kita boleh bermula daripada masalah operasi sebelum memilih teknologi.</p></div><a className="button contact-button" href="mailto:hello@uniras.my">hello@uniras.my</a></div></section>
<footer className="footer shell"><div className="brand"><span className="brand-mark">U</span><span>UNIRAS</span></div><p>UNIRAS SDN. BHD.<br/>No. Pendaftaran 1478108T / 202201032411</p><p>Produk Digital · Aplikasi · Sistem Perniagaan</p><p>© 2026 UNIRAS SDN. BHD.</p></footer>
</main>}
